### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by Trigger-broom-289** [antiguru/ykush2#1]
Greetings,

I'm trying to compile ykush2 from your repo https://github.com/antiguru/ykush2 but I'm not getting anywhere with it.

root@heidenrod-obs:/home/ykush2# pwd
/home/ykush2
root@heidenrod-obs:/home/ykush2# ls -la

total 44
drwxr-xr-x 4 root root 4096 Feb  9 22:25 .
drwxr-xr-x 3 root root 4096 Feb  9 22:21 ..
drwxr-xr-x 3 root root 4096 Feb  9 22:21 debian
drwxr-xr-x 8 root root 4096 Feb  9 22:21 .git
-rw-r--r-- 1 root root  362 Feb  9 22:21 .gitignore
-rw-r--r-- 1 root root 1108 Feb  9 22:21 LICENSE
-rw-r--r-- 1 root root 6359 Feb  9 22:21 main.c
-rw-r--r-- 1 root root  462 Feb  9 22:21 Makefile
-rw-r--r-- 1 root root   73 Feb  9 22:21 README.md
-rw-r--r-- 1 root root  261 Feb  9 22:21 usbcom.h
root@heidenrod-obs:/home/ykush2# make
cc -std=c99 -lusb-1.0 main.c -o ykush2
main.c: In function ‘main’:
main.c:153:13: warning: implicit declaration of function ‘libusb_strerror’ [-Wimplicit-function-declaration]
/tmp/ccoHuQNN.o: In function `main':
main.c:(.text+0x52a): undefined reference to`libusb_strerror'
main.c:(.text+0x598): undefined reference to `libusb_strerror'
main.c:(.text+0x606): undefined reference to`libusb_strerror'
main.c:(.text+0x6b0): undefined reference to `libusb_strerror'
main.c:(.text+0x734): undefined reference to`libusb_strerror'
collect2: ld returned 1 exit status
make: **\* [ykush2] Error 1
root@heidenrod-obs:/home/ykush2# cat /etc/debian_version 
7.8
root@heidenrod-obs:/home/ykush2# 

Are you able to help me out please?

Regards
Stephane

**Comment by antiguru** [comment]
Hi Stephane,
thanks for reporting this. It seems there are some versions of libusb-1.0 that have the libusb_strerror function and others don't have it. As it is more for convenience I'm just removing all references to it. If the problem persists just let me know :)
Moritz

**Comment by Trigger-broom-289** [comment]
Hi Moritz

thanks for getting back to me, appreciated it really.
Are you pushing a new code to github or would I need to edit the main.c
file?


Stephane

**Comment by Trigger-broom-289** [comment]
Hi,

It's fixed now, thanks SO much for a quick response !!! awesome.

root@heidenrod-obs:/home/ykush2# ./ykush2 
Usage:
 ykush2 [-l]
 ykush2 [-h hub] {-d|-u} {port|a}
root@heidenrod-obs:/home/ykush2# ./ykush2 -l
1: 04d8:0042 Yepkit Lda./YKUSH/YKP0001
2: 04d8:0042 Yepkit Lda./YKUSH/YKP0001
root@heidenrod-obs:/home/ykush2# 

Regards
Stephane

**Comment by Trigger-broom-289** [comment]
Just found the following error with that commit.

root@heidenrod-obs:/home/ykush2# make install
mkdir -p /  /usr//bin
/usr/bin/install ykush2 /  /usr//bin
/usr/bin/install: omitting directory `/'
make: **\* [install] Error 1
root@heidenrod-obs:/home/ykush2# 

Regards
Stephane

**Comment by antiguru** [comment]
You're welcome! You can also build a Debian package using `dpkg-buildpackage` from the ykush2 directory, which can be installed using `dpkg -i ../ykush2...deb`.

**Comment by antiguru** [comment]
Make install should work now as well. See 7a6d3bd.

**Comment by Trigger-broom-289** [comment]
cool thanks, I've used the dpkg-buildpackage and that worked great, package is compiled/installed and I'm using it. Great work.

I have two boards connected to my odroid-c1 running Debian. This works great for my project.

Regards
Stephane

**Comment by Trigger-broom-289** [comment]
Thanks for your speedy work, much appreciated.

**Comment by antiguru** [comment]
Happy to hear that :+1:

**Comment by paketecuento** [comment]
looks like the problem still there. Im using Ubuntu 14.04.1 LTS Trusty.

paco@ubuntu:~/ykush2-master$ sudo make
cc -std=c99 -lusb-1.0 main.c -o ykush2
/tmp/ccWaAfIo.o: En la función `main':
main.c:(.text+0x1d0): referencia a`libusb_init' sin definir
main.c:(.text+0x1e7): referencia a `libusb_error_name' sin definir
main.c:(.text+0x21f): referencia a`libusb_get_device_list' sin definir
main.c:(.text+0x25f): referencia a `libusb_get_device_descriptor' sin definir
main.c:(.text+0x276): referencia a`libusb_error_name' sin definir
main.c:(.text+0x30e): referencia a `libusb_open' sin definir
main.c:(.text+0x352): referencia a`libusb_get_string_descriptor_ascii' sin definir
main.c:(.text+0x369): referencia a `libusb_close' sin definir
main.c:(.text+0x399): referencia a`libusb_get_string_descriptor_ascii' sin definir
main.c:(.text+0x3b0): referencia a `libusb_close' sin definir
main.c:(.text+0x3e0): referencia a`libusb_get_string_descriptor_ascii' sin definir
main.c:(.text+0x3f7): referencia a `libusb_close' sin definir
main.c:(.text+0x42f): referencia a`libusb_close' sin definir
main.c:(.text+0x475): referencia a `libusb_open' sin definir
main.c:(.text+0x48c): referencia a`libusb_error_name' sin definir
main.c:(.text+0x510): referencia a `libusb_detach_kernel_driver' sin definir
main.c:(.text+0x52e): referencia a`libusb_error_name' sin definir
main.c:(.text+0x561): referencia a `libusb_set_configuration' sin definir
main.c:(.text+0x578): referencia a`libusb_error_name' sin definir
main.c:(.text+0x5ab): referencia a `libusb_claim_interface' sin definir
main.c:(.text+0x5c2): referencia a`libusb_error_name' sin definir
main.c:(.text+0x638): referencia a `libusb_interrupt_transfer' sin definir
main.c:(.text+0x64f): referencia a`libusb_error_name' sin definir
main.c:(.text+0x6a5): referencia a `libusb_interrupt_transfer' sin definir
main.c:(.text+0x6bc): referencia a`libusb_error_name' sin definir
main.c:(.text+0x71a): referencia a `libusb_close' sin definir
main.c:(.text+0x72e): referencia a`libusb_free_device_list' sin definir
main.c:(.text+0x73b): referencia a `libusb_exit' sin definir
collect2: error: ld returned 1 exit status
make: **\* [ykush2] Error 1

**Comment by antiguru** [comment]
Hi @paketecuento,
this is a different problem: Did you install libusb-1.0-0-dev? It looks very much like it is not available at all as those linker errors are essential functions of the library. Btw, don't run make as sudo.
Moritz

**Comment by Trigger-broom-289** [comment]
Hi Moritz,

just installed Ubuntu 14.10 on my Odroid-C1 (had to replace Debian) and I cannot compile it.
Same error as the one above.

root@bigsmall:/home/ykush2-master# make
cc -std=c99 -lusb-1.0 main.c -o ykush2
/tmp/ccUmHFzO.o: In function `main':
main.c:(.text+0x1ac): undefined reference to`libusb_init'
main.c:(.text+0x1c4): undefined reference to `libusb_error_name'
main.c:(.text+0x1f0): undefined reference to`libusb_get_device_list'
main.c:(.text+0x21a): undefined reference to `libusb_get_device_descriptor'
main.c:(.text+0x232): undefined reference to`libusb_error_name'
main.c:(.text+0x292): undefined reference to `libusb_open'
main.c:(.text+0x2b8): undefined reference to`libusb_get_string_descriptor_ascii'
main.c:(.text+0x2c8): undefined reference to `libusb_close'
main.c:(.text+0x2da): undefined reference to`libusb_get_string_descriptor_ascii'
main.c:(.text+0x2ea): undefined reference to `libusb_close'
main.c:(.text+0x2fc): undefined reference to`libusb_get_string_descriptor_ascii'
main.c:(.text+0x30c): undefined reference to `libusb_close'
main.c:(.text+0x32e): undefined reference to`libusb_close'
main.c:(.text+0x360): undefined reference to `libusb_open'
main.c:(.text+0x378): undefined reference to`libusb_error_name'
main.c:(.text+0x3d6): undefined reference to `libusb_detach_kernel_driver'
main.c:(.text+0x3f6): undefined reference to`libusb_error_name'
main.c:(.text+0x414): undefined reference to `libusb_set_configuration'
main.c:(.text+0x42c): undefined reference to`libusb_error_name'
main.c:(.text+0x44a): undefined reference to `libusb_claim_interface'
main.c:(.text+0x462): undefined reference to`libusb_error_name'
main.c:(.text+0x4aa): undefined reference to `libusb_interrupt_transfer'
main.c:(.text+0x4c2): undefined reference to`libusb_error_name'
main.c:(.text+0x4f0): undefined reference to `libusb_interrupt_transfer'
main.c:(.text+0x508): undefined reference to`libusb_error_name'
main.c:(.text+0x54a): undefined reference to `libusb_close'
main.c:(.text+0x558): undefined reference to`libusb_free_device_list'
main.c:(.text+0x568): undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'ykush2' failed
make: **\* [ykush2] Error 1
root@bigsmall:/home/ykush2-master# 

root@bigsmall:/home/ykush2-master# dpkg -l | grep libusb
ii  libusb-0.1-4:armhf            2:0.1.12-24                      armhf        userspace USB programming library
ii  libusb-1.0-0:armhf            2:1.0.17-1ubuntu2                armhf        userspace USB programming library
ii  libusb-1.0-0-dbg:armhf        2:1.0.17-1ubuntu2                armhf        userspace USB programming library development files
ii  libusb-1.0-0-dev:armhf        2:1.0.17-1ubuntu2                armhf        userspace USB programming library development files
ii  libusb-1.0-doc                2:1.0.17-1ubuntu2                all          documentation for userspace USB programming
ii  libusb-dev                    2:0.1.12-24                      armhf        userspace USB programming library development files
root@bigsmall:/home/ykush2-master#

Regards
Stephane

**Comment by Trigger-broom-289** [comment]
It's fixed,

after some googling I've found the following:

## https://bugs.launchpad.net/ubuntu/+source/libusb/+bug/920948

## Newer versions of GCC require the linker flags to be placed after the objects to be linked. 

I was able to compile it with:

 cc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -Wl,-Bsymbolic-functions -Wl,-z,relro main.c -lusb-1.0 -o ykush2

root@heidenrod-obs:/home/ykush2# ./ykush2 -l
1: 04d8:0042 Yepkit Lda./YKUSH/YKP0001
2: 04d8:0042 Yepkit Lda./YKUSH/YK10005
root@heidenrod-obs:/home/ykush2#

**Comment by Trigger-broom-289** [comment]
in Makefile:

$(CC) $(CFLAGS) $(SOURCES) $(LDFLAGS) -o $@

instead of

$(CC) $(CFLAGS) $(LDFLAGS) $(SOURCES) -o $@

**Comment by antiguru** [comment]
Oh, that's interesting. Great you found a solution! I'll update the repo accordingly.
